const { v4: uuid } = require('uuid');

const users = [];
const listings = [];
const offers = [];
const messages = [];
const watchlist = [];
const reports = [];
const payments = [];

const SELLERS = [
  {
    id: 'seller-ananya',
    name: 'Ananya Verma',
    email: 'ananya@websitesell.online',
    phone: '9811100011',
    rating: 4.9,
    reviews: 21,
    createdAt: '2022-01-15T00:00:00.000Z',
  },
  {
    id: 'seller-rahul',
    name: 'Rahul Mehta',
    email: 'rahul@websitesell.online',
    phone: '9822200022',
    rating: 4.8,
    reviews: 26,
    createdAt: '2022-01-01T00:00:00.000Z',
  },
  {
    id: 'seller-priya',
    name: 'Priya Nair',
    email: 'priya@websitesell.online',
    phone: '9833300033',
    rating: 4.7,
    reviews: 12,
    createdAt: '2023-03-01T00:00:00.000Z',
  },
];

const WEBSITE_LISTINGS = [
  {
    id: 'taskflow-pro',
    name: 'TaskFlow Pro',
    subtitle: 'Make productivity simple for teams',
    category: 'Tools & Utilities',
    price: 45000,
    monthlyRevenue: 8000,
    traffic: '12K',
    domainAge: '1 Year',
    platform: 'Custom',
    monetization: 'SaaS plans',
    included: 'Codebase, Stripe/Razorpay integration',
    support: '2 Weeks Support',
    lastUpdated: '01 Sep 2025',
    listedOn: '05 Sep 2025',
    description:
      'Team productivity workspace with boards, docs and lightweight automation, used by Indian SMEs to run day-to-day delivery.',
    keyFeatures: ['Kanban boards', 'Shared docs', 'No-code automations'],
    whySelling: 'Side project; focusing on a full-time role.',
    techStack: ['React', 'Node.js', 'MongoDB'],
    monthlySeries: [4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8],
    userStats: { downloads: '12K visitors', users: '180 teams', rating: '4.5', retention: '70%' },
    cover: 'taskflow',
    sellerId: 'seller-rahul',
    featured: true,
    createdAt: '2025-09-05T00:00:00.000Z',
  },
  {
    id: 'travel-guide-blog',
    name: 'Travel Guide Blog',
    subtitle: 'Explore the world with destination guides',
    category: 'Travel & Lifestyle',
    price: 120000,
    monthlyRevenue: 25000,
    traffic: '45K',
    domainAge: '2 Years',
    platform: 'WordPress',
    monetization: 'Ads, Affiliates',
    included: 'Domain, Hosting setup, Content, Analytics',
    support: '2 Weeks Support',
    lastUpdated: '02 Sep 2025',
    listedOn: '12 Sep 2025',
    description:
      'India-first travel magazine with destination guides, affiliate hotel bookings and a growing email list ranked well for hill-station and weekend-getaway queries.',
    keyFeatures: ['Evergreen destination guides', 'Affiliate hotel widgets', 'Email list of 18,000 readers'],
    whySelling: 'Moving focus to a SaaS product and want a travel publisher to scale this brand.',
    techStack: ['WordPress', 'PHP', 'MySQL'],
    monthlySeries: [8, 10, 11, 12, 14, 16, 18, 20, 21, 23, 24, 25],
    userStats: { downloads: '45K visitors', users: '12K', rating: '4.7', retention: '62%' },
    cover: 'travel',
    sellerId: 'seller-ananya',
    featured: true,
    createdAt: '2025-09-12T00:00:00.000Z',
  },
  {
    id: 'recipe-world',
    name: 'Recipe World',
    subtitle: 'Indian recipes with step-by-step photos',
    category: 'Food & Recipes',
    price: 60000,
    monthlyRevenue: 9000,
    traffic: '28K',
    domainAge: '3 Years',
    platform: 'WordPress',
    monetization: 'Ads, Sponsored posts',
    included: 'Domain, Content, Analytics, Social handles',
    support: '2 Weeks Support',
    lastUpdated: '28 Aug 2025',
    listedOn: '08 Sep 2025',
    description:
      'Recipe portal with 1,200+ indexed recipes, strong Pinterest traffic and brand sponsorships from kitchen appliance sellers.',
    keyFeatures: ['1,200+ recipes', 'Pinterest traffic engine', 'Sponsorship ready'],
    whySelling: 'Shifting to a food delivery venture.',
    techStack: ['WordPress', 'PHP'],
    monthlySeries: [5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9],
    userStats: { downloads: '28K visitors', users: '8K', rating: '4.6', retention: '55%' },
    cover: 'food',
    sellerId: 'seller-priya',
    featured: false,
    createdAt: '2025-09-08T00:00:00.000Z',
  },
  {
    id: 'greenkart-store',
    name: 'GreenKart Store',
    subtitle: 'Online nursery for plants and seeds',
    category: 'E-commerce',
    price: 95000,
    monthlyRevenue: 18000,
    traffic: '22K',
    domainAge: '2 Years',
    platform: 'Shopify',
    monetization: 'Product sales',
    included: 'Store, Vendor accounts, Inventory sheet, Brand',
    support: '1 Month Support',
    lastUpdated: '30 Aug 2025',
    listedOn: '09 Sep 2025',
    description:
      'Nursery and gardening e-commerce store with repeat customers, 4,000+ orders delivered and a reliable courier tie-up.',
    keyFeatures: ['4,000+ orders', 'Repeat customer base', 'Live courier integration'],
    whySelling: 'Relocating and cannot manage warehouse operations.',
    techStack: ['Shopify', 'Liquid'],
    monthlySeries: [10, 11, 12, 13, 14, 15, 16, 16, 17, 17, 18, 18],
    userStats: { downloads: '22K visitors', users: '5K buyers', rating: '4.8', retention: '66%' },
    cover: 'plants',
    sellerId: 'seller-rahul',
    featured: true,
    createdAt: '2025-09-09T00:00:00.000Z',
  },
  {
    id: 'aitify-hub',
    name: 'Aitify Hub',
    subtitle: 'AI tools directory for Indian creators',
    category: 'Technology',
    price: 150000,
    monthlyRevenue: 32000,
    traffic: '60K',
    domainAge: '2 Years',
    platform: 'Custom',
    monetization: 'SaaS, Ads',
    included: 'Codebase, Brand, User base, Newsletter',
    support: '1 Month Support',
    lastUpdated: '04 Sep 2025',
    listedOn: '11 Sep 2025',
    description:
      'Directory of AI writing, image and automation tools with paid listings, affiliate commissions and a 22,000-subscriber newsletter.',
    keyFeatures: ['Tool directory', 'Paid placements', '22K newsletter subscribers'],
    whySelling: 'Founder joining an AI startup and wants a dedicated owner.',
    techStack: ['Next.js', 'Node.js', 'PostgreSQL'],
    monthlySeries: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 31, 32],
    userStats: { downloads: '60K visitors', users: '9K', rating: '4.8', retention: '58%' },
    cover: 'aitify',
    sellerId: 'seller-ananya',
    featured: true,
    createdAt: '2025-09-11T00:00:00.000Z',
  },
  {
    id: 'news-portal',
    name: 'News Portal',
    subtitle: 'Regional news with high ad revenue',
    category: 'News & Media',
    price: 135000,
    monthlyRevenue: 27000,
    traffic: '80K',
    domainAge: '4 Years',
    platform: 'WordPress',
    monetization: 'AdSense, Direct ads',
    included: 'Domain, Content archive, Writer network',
    support: '2 Weeks Support',
    lastUpdated: '26 Aug 2025',
    listedOn: '07 Sep 2025',
    description:
      'Hindi regional news site with a 6-member contributor network, steady AdSense income and 80K monthly pageviews.',
    keyFeatures: ['80K monthly views', 'Writer network', 'AdSense approved'],
    whySelling: 'Owner moving to a print publication.',
    techStack: ['WordPress', 'PHP', 'MySQL'],
    monthlySeries: [18, 19, 20, 21, 22, 23, 24, 25, 26, 26, 27, 27],
    userStats: { downloads: '80K visitors', users: '30K', rating: '4.4', retention: '48%' },
    cover: 'newsportal',
    sellerId: 'seller-priya',
    featured: false,
    createdAt: '2025-09-07T00:00:00.000Z',
  },
  {
    id: 'studynest',
    name: 'StudyNest',
    subtitle: 'Online notes and test series portal',
    category: 'Education',
    price: 70000,
    monthlyRevenue: 14000,
    traffic: '35K',
    domainAge: '1 Year',
    platform: 'Laravel',
    monetization: 'Subscriptions',
    included: 'Codebase, Question bank, Payment setup',
    support: '1 Month Support',
    lastUpdated: '03 Sep 2025',
    listedOn: '10 Sep 2025',
    description:
      'Exam-prep portal selling notes and test series for state government exams with 3,500 paid subscribers.',
    keyFeatures: ['Test series engine', '3,500 paid users', 'Razorpay subscriptions'],
    whySelling: 'Partner exited and I cannot run academics alone.',
    techStack: ['Laravel', 'MySQL', 'Tailwind'],
    monthlySeries: [6, 7, 8, 9, 10, 10, 11, 12, 13, 13, 14, 14],
    userStats: { downloads: '35K visitors', users: '3.5K paid', rating: '4.7', retention: '68%' },
    cover: 'studynest',
    sellerId: 'seller-rahul',
    featured: false,
    createdAt: '2025-09-10T00:00:00.000Z',
  },
  {
    id: 'finflow-blog',
    name: 'FinFlow Blog',
    subtitle: 'Personal finance and investing content',
    category: 'Finance',
    price: 180000,
    monthlyRevenue: 38000,
    traffic: '95K',
    domainAge: '3 Years',
    platform: 'WordPress',
    monetization: 'Ads, Affiliates, Leads',
    included: 'Domain, Content, Email list, Lead partners',
    support: '1 Month Support',
    lastUpdated: '05 Sep 2025',
    listedOn: '13 Sep 2025',
    description:
      'Personal finance blog ranked for mutual fund, credit card and tax queries, monetized via ads and partner leads.',
    keyFeatures: ['95K monthly views', 'Lead gen deals', '40K email subscribers'],
    whySelling: 'Compliance overhead as a registered advisor.',
    techStack: ['WordPress', 'PHP'],
    monthlySeries: [22, 24, 26, 27, 29, 31, 33, 34, 35, 36, 37, 38],
    userStats: { downloads: '95K visitors', users: '40K', rating: '4.9', retention: '71%' },
    cover: 'finflow',
    sellerId: 'seller-ananya',
    featured: true,
    createdAt: '2025-09-13T00:00:00.000Z',
  },
  {
    id: 'techbyte-daily',
    name: 'TechByte Daily',
    subtitle: 'Gadget reviews and buying guides',
    category: 'Technology',
    price: 85000,
    monthlyRevenue: 16000,
    traffic: '42K',
    domainAge: '2 Years',
    platform: 'Custom',
    monetization: 'Affiliate, Sponsored reviews',
    included: 'Domain, Content, YouTube channel, Deals',
    support: '2 Weeks Support',
    lastUpdated: '29 Aug 2025',
    listedOn: '06 Sep 2025',
    description:
      'Consumer tech review site with Amazon affiliate income, sponsored review pipeline and a linked YouTube channel.',
    keyFeatures: ['Amazon affiliate income', 'YouTube channel', 'Review pipeline'],
    whySelling: 'Moving abroad for higher studies.',
    techStack: ['Next.js', 'Sanity', 'Vercel'],
    monthlySeries: [9, 10, 11, 12, 12, 13, 14, 14, 15, 15, 16, 16],
    userStats: { downloads: '42K visitors', users: '15K', rating: '4.6', retention: '60%' },
    cover: 'generic',
    sellerId: 'seller-priya',
    featured: false,
    createdAt: '2025-09-06T00:00:00.000Z',
  },
  {
    id: 'urbanstay-rentals',
    name: 'UrbanStay Rentals',
    subtitle: 'Serviced apartment booking platform',
    category: 'Travel & Lifestyle',
    price: 210000,
    monthlyRevenue: 45000,
    traffic: '18K',
    domainAge: '3 Years',
    platform: 'Custom',
    monetization: 'Booking commission',
    included: 'Platform, Owner network, Brand, Support docs',
    support: '2 Months Support',
    lastUpdated: '31 Aug 2025',
    listedOn: '14 Sep 2025',
    description:
      'Booking platform for 120 serviced apartments across Bengaluru and Pune, earning commission on every confirmed stay.',
    keyFeatures: ['120 partner properties', 'Commission per booking', 'Owner dashboard'],
    whySelling: 'Scaling a hotel chain instead of a marketplace.',
    techStack: ['React', 'Express', 'PostgreSQL'],
    monthlySeries: [30, 32, 34, 36, 38, 40, 41, 42, 43, 44, 44, 45],
    userStats: { downloads: '18K visitors', users: '120 owners', rating: '4.7', retention: '75%' },
    cover: 'generic',
    sellerId: 'seller-rahul',
    featured: false,
    createdAt: '2025-09-14T00:00:00.000Z',
  },
];

const APP_LISTINGS = [
  {
    id: 'habit-tracker-pro',
    name: 'Habit Tracker Pro',
    subtitle: 'Build better routines every day',
    category: 'Health & Fitness',
    price: 50000,
    monthlyRevenue: 12000,
    downloads: '100K+',
    appSize: '14 MB',
    minAndroid: 'Android 6.0+',
    platform: 'Android',
    monetization: 'Freemium, IAP',
    included: 'Source Code, Play assets, Documentation',
    support: '1 Month Support',
    lastUpdated: '18 Aug 2025',
    listedOn: '02 Sep 2025',
    description:
      'Habit streaks, reminders and wellness reports with a loyal daily-active user base and strong Play Store ratings.',
    keyFeatures: ['Streak engine', 'Smart reminders', 'Wellness insights'],
    whySelling: 'Team shifting to wearable hardware.',
    techStack: ['Flutter', 'Firebase'],
    monthlySeries: [6, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12],
    userStats: { downloads: '100K+', users: '28K', rating: '4.8', retention: '74%' },
    cover: 'habit',
    sellerId: 'seller-ananya',
    featured: true,
    createdAt: '2025-09-02T00:00:00.000Z',
  },
  {
    id: 'study-master',
    name: 'Study Master',
    subtitle: 'Complete learning app with mock tests',
    category: 'Education',
    price: 40000,
    monthlyRevenue: 8000,
    downloads: '50K+',
    appSize: '22 MB',
    minAndroid: 'Android 5.0+',
    platform: 'Android',
    monetization: 'Ads, Subscriptions',
    included: 'Source Code, Question bank, Play assets',
    support: '2 Weeks Support',
    lastUpdated: '22 Aug 2025',
    listedOn: '04 Sep 2025',
    description:
      'Exam-prep app with mock tests, daily quizzes and notes for competitive exams, with 50K+ installs and paid subscribers.',
    keyFeatures: ['Mock tests', 'Daily quizzes', 'Offline notes'],
    whySelling: 'Founder pursuing a full-time job.',
    techStack: ['Kotlin', 'Room DB'],
    monthlySeries: [4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8],
    userStats: { downloads: '50K+', users: '12K', rating: '4.6', retention: '63%' },
    cover: 'study',
    sellerId: 'seller-rahul',
    featured: false,
    createdAt: '2025-09-04T00:00:00.000Z',
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    subtitle: 'Track spends and budgets offline',
    category: 'Finance',
    price: 35000,
    monthlyRevenue: 7000,
    downloads: '75K+',
    appSize: '11 MB',
    minAndroid: 'Android 5.0+',
    platform: 'Android',
    monetization: 'Ads, Pro unlock',
    included: 'Source Code, Play assets, Ad account setup',
    support: '2 Weeks Support',
    lastUpdated: '20 Aug 2025',
    listedOn: '03 Sep 2025',
    description:
      'Offline-first expense manager with category budgets, charts and export, popular with first-time budgeters.',
    keyFeatures: ['Offline tracking', 'Budget alerts', 'CSV export'],
    whySelling: 'Want to focus on my accounting SaaS.',
    techStack: ['Java', 'SQLite'],
    monthlySeries: [3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7],
    userStats: { downloads: '75K+', users: '20K', rating: '4.4', retention: '58%' },
    cover: 'finance',
    sellerId: 'seller-priya',
    featured: false,
    createdAt: '2025-09-03T00:00:00.000Z',
  },
  {
    id: 'photo-editor-pro',
    name: 'Photo Editor Pro',
    subtitle: 'Filters, portraits and collages',
    category: 'Photography',
    price: 45000,
    monthlyRevenue: 10000,
    downloads: '50K+',
    appSize: '28 MB',
    minAndroid: 'Android 6.0+',
    platform: 'Android',
    monetization: 'Ads, Pro unlock',
    included: 'Source Code, Play assets, Filters pack',
    support: '1 Month Support',
    lastUpdated: '12 Aug 2025',
    listedOn: '25 Aug 2025',
    description:
      'Portrait retouch, filters and collage maker popular with creators on the Play Store.',
    keyFeatures: ['AI filters', 'Collage maker', 'Portrait retouch'],
    whySelling: 'Focusing on a camera hardware kit.',
    techStack: ['Kotlin', 'OpenGL'],
    monthlySeries: [4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10],
    userStats: { downloads: '50K+', users: '14K', rating: '4.5', retention: '49%' },
    cover: 'photo',
    sellerId: 'seller-rahul',
    featured: true,
    createdAt: '2025-08-25T00:00:00.000Z',
  },
  {
    id: 'ludo-star',
    name: 'Ludo Star',
    subtitle: 'Online Ludo with real-time rooms',
    category: 'Games',
    price: 90000,
    monthlyRevenue: 22000,
    downloads: '500K+',
    appSize: '42 MB',
    minAndroid: 'Android 6.0+',
    platform: 'Android',
    monetization: 'Ads, In-app coins',
    included: 'Source Code, Server code, Play assets',
    support: '1 Month Support',
    lastUpdated: '15 Aug 2025',
    listedOn: '01 Sep 2025',
    description:
      'Real-time multiplayer Ludo with matchmaking, chat and coin economy, retaining a healthy daily active base.',
    keyFeatures: ['Realtime multiplayer', 'Coin economy', 'Leaderboards'],
    whySelling: 'Bootstrapping a larger gaming studio.',
    techStack: ['Unity', 'Photon', 'Node.js'],
    monthlySeries: [14, 15, 16, 17, 18, 19, 20, 20, 21, 21, 22, 22],
    userStats: { downloads: '500K+', users: '60K', rating: '4.5', retention: '52%' },
    cover: 'ludo',
    sellerId: 'seller-ananya',
    featured: false,
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'weather-live',
    name: 'Weather Live',
    subtitle: 'Hyperlocal weather and radar',
    category: 'Weather',
    price: 30000,
    monthlyRevenue: 6000,
    downloads: '200K+',
    appSize: '9 MB',
    minAndroid: 'Android 5.0+',
    platform: 'Android',
    monetization: 'Ads',
    included: 'Source Code, API keys, Play assets',
    support: '1 Month Support',
    lastUpdated: '10 Aug 2025',
    listedOn: '28 Aug 2025',
    description:
      'Hyperlocal forecasts, rain radar and severe weather alerts with strong retention during monsoon.',
    keyFeatures: ['Minute-level rain', 'Radar map', 'Weather alerts'],
    whySelling: 'Weather is a side project and I need to free up bandwidth.',
    techStack: ['Kotlin', 'OpenWeather'],
    monthlySeries: [4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6],
    userStats: { downloads: '200K+', users: '40K', rating: '4.3', retention: '61%' },
    cover: 'weather',
    sellerId: 'seller-priya',
    featured: false,
    createdAt: '2025-08-28T00:00:00.000Z',
  },
  {
    id: 'recipe-book',
    name: 'Recipe Book',
    subtitle: 'Offline Indian recipes with videos',
    category: 'Food & Drink',
    price: 38000,
    monthlyRevenue: 7500,
    downloads: '120K+',
    appSize: '26 MB',
    minAndroid: 'Android 5.0+',
    platform: 'Android',
    monetization: 'Ads, IAP',
    included: 'Source Code, Recipe content, Play assets',
    support: '2 Weeks Support',
    lastUpdated: '19 Aug 2025',
    listedOn: '30 Aug 2025',
    description:
      'Offline recipe app with 900+ Indian recipes, step videos and a shopping-list generator.',
    keyFeatures: ['900+ recipes', 'Step videos', 'Shopping list'],
    whySelling: 'Content licensing deal taking my time.',
    techStack: ['Flutter', 'SQLite'],
    monthlySeries: [4, 5, 5, 6, 6, 6, 7, 7, 7, 7, 7, 8],
    userStats: { downloads: '120K+', users: '25K', rating: '4.6', retention: '57%' },
    cover: 'recipebook',
    sellerId: 'seller-rahul',
    featured: false,
    createdAt: '2025-08-30T00:00:00.000Z',
  },
  {
    id: 'daily-planner',
    name: 'Daily Planner',
    subtitle: 'Tasks, calendar and reminders',
    category: 'Productivity',
    price: 42000,
    monthlyRevenue: 9000,
    downloads: '80K+',
    appSize: '13 MB',
    minAndroid: 'Android 6.0+',
    platform: 'Android',
    monetization: 'Freemium, IAP',
    included: 'Source Code, Play assets, Widgets',
    support: '2 Weeks Support',
    lastUpdated: '24 Aug 2025',
    listedOn: '31 Aug 2025',
    description:
      'Daily planner combining tasks, calendar and reminders with home-screen widgets and a clean dark mode.',
    keyFeatures: ['Task planner', 'Calendar sync', 'Home widgets'],
    whySelling: 'Joining a productivity startup.',
    techStack: ['Kotlin', 'WorkManager'],
    monthlySeries: [5, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, 9],
    userStats: { downloads: '80K+', users: '18K', rating: '4.7', retention: '65%' },
    cover: 'planner',
    sellerId: 'seller-ananya',
    featured: false,
    createdAt: '2025-08-31T00:00:00.000Z',
  },
  {
    id: 'fitindia-gym',
    name: 'FitIndia Gym',
    subtitle: 'Home workouts and diet plans',
    category: 'Health & Fitness',
    price: 55000,
    monthlyRevenue: 11000,
    downloads: '150K+',
    appSize: '30 MB',
    minAndroid: 'Android 6.0+',
    platform: 'Android',
    monetization: 'Subscriptions, Ads',
    included: 'Source Code, Workout library, Play assets',
    support: '1 Month Support',
    lastUpdated: '21 Aug 2025',
    listedOn: '27 Aug 2025',
    description:
      'Home workout app with diet plans, progress tracking and a paid subscription tier, popular in tier-2 cities.',
    keyFeatures: ['Guided workouts', 'Diet plans', 'Progress charts'],
    whySelling: 'Scaling an offline fitness studio.',
    techStack: ['Kotlin', 'Firebase'],
    monthlySeries: [6, 7, 7, 8, 8, 9, 9, 10, 10, 10, 11, 11],
    userStats: { downloads: '150K+', users: '32K', rating: '4.5', retention: '60%' },
    cover: 'generic',
    sellerId: 'seller-priya',
    featured: false,
    createdAt: '2025-08-27T00:00:00.000Z',
  },
  {
    id: 'bharat-news',
    name: 'Bharat News',
    subtitle: 'Fast regional news in 8 languages',
    category: 'Entertainment',
    price: 65000,
    monthlyRevenue: 13000,
    downloads: '250K+',
    appSize: '18 MB',
    minAndroid: 'Android 6.0+',
    platform: 'Android',
    monetization: 'Ads, Sponsored content',
    included: 'Source Code, Content feeds, Play assets',
    support: '2 Weeks Support',
    lastUpdated: '17 Aug 2025',
    listedOn: '29 Aug 2025',
    description:
      'Regional news reader in 8 Indian languages with push alerts, video feed and strong ad revenue.',
    keyFeatures: ['8 languages', 'Push alerts', 'Video feed'],
    whySelling: 'Moving to a newsroom product role.',
    techStack: ['Flutter', 'REST APIs'],
    monthlySeries: [7, 8, 9, 9, 10, 11, 11, 12, 12, 12, 13, 13],
    userStats: { downloads: '250K+', users: '48K', rating: '4.4', retention: '54%' },
    cover: 'generic',
    sellerId: 'seller-rahul',
    featured: false,
    createdAt: '2025-08-29T00:00:00.000Z',
  },
];

function addSellers() {
  let added = 0;
  for (const seller of SELLERS) {
    if (users.some((u) => u.id === seller.id)) continue;
    users.push({
      ...seller,
      password: uuid(),
      role: 'user',
      verified: true,
      blocked: false,
      extraListingSlots: 0,
    });
    added += 1;
  }
  return added;
}

function addListings(seedListings) {
  let added = 0;
  for (const item of seedListings) {
    if (listings.some((l) => l.id === item.id)) continue;
    listings.push({
      type: item.type,
      subtitle: item.description.slice(0, 140),
      downloads: '',
      traffic: '',
      screenshots: [],
      contact: '',
      phone: '',
      liveUrl: '',
      language: 'English',
      reviews: 0,
      rating: 0,
      ...item,
      status: 'approved',
    });
    added += 1;
  }
  return added;
}

function seed() {
  const sellers = addSellers();
  const websites = addListings(
    WEBSITE_LISTINGS.map((item) => ({ ...item, type: 'website' }))
  );
  const apps = addListings(APP_LISTINGS.map((item) => ({ ...item, type: 'app' })));
  return sellers + websites + apps;
}

module.exports = { users, listings, offers, messages, watchlist, reports, payments, seed };
