const { v4: uuid } = require('uuid');

const users = [];
const listings = [];
const offers = [];
const messages = [];
const watchlist = [];

function seed() {
  if (users.length) return;

  const admin = {
    id: uuid(),
    name: 'Admin',
    email: 'admin@nexmarket.in',
    password: 'admin123',
    role: 'admin',
    verified: true,
    createdAt: '2022-01-10T00:00:00.000Z',
  };
  const anand = {
    id: uuid(),
    name: 'Anand Sharma',
    email: 'anand@seller.in',
    password: 'seller123',
    role: 'seller',
    verified: true,
    rating: 4.9,
    reviews: 18,
    earnings: 285000,
    createdAt: '2022-01-15T00:00:00.000Z',
  };
  const rahul = {
    id: uuid(),
    name: 'Rahul Kumar',
    email: 'rahul@seller.in',
    password: 'seller123',
    role: 'seller',
    verified: true,
    rating: 4.8,
    reviews: 24,
    earnings: 0,
    createdAt: '2022-01-01T00:00:00.000Z',
  };
  const arjun = {
    id: uuid(),
    name: 'Arjun Mehta',
    email: 'arjun@buyer.in',
    password: 'buyer123',
    role: 'buyer',
    verified: false,
    createdAt: new Date().toISOString(),
  };
  users.push(admin, anand, rahul, arjun);

  const listed = (d) => d;

  listings.push(
    {
      id: 'travel-guide-blog',
      type: 'website',
      name: 'Travel Guide Blog',
      subtitle: 'Explore the world with destination guides',
      category: 'Travel & Lifestyle',
      price: 120000,
      monthlyRevenue: 25000,
      traffic: '45K',
      downloads: '',
      rating: 4.7,
      reviews: 86,
      appSize: '',
      domainAge: '2 Years',
      minAndroid: '',
      language: 'English',
      monetization: 'Ads, Affiliates',
      included: 'Domain, Hosting setup, Content, Analytics',
      support: '2 Weeks Support',
      lastUpdated: '02 Sep 2025',
      listedOn: '12 Sep 2025',
      description:
        'India-first travel magazine with destination guides, affiliate hotel bookings and a growing email list. Strong SEO for hill-station and weekend-getaway queries.',
      keyFeatures: [
        'Evergreen destination guides',
        'Affiliate hotel and tour widgets',
        'Email list of 18,000 readers',
        'Clean WordPress theme',
      ],
      whySelling: 'Moving focus to a SaaS product and want a travel publisher to scale this brand.',
      techStack: ['WordPress', 'PHP', 'MySQL'],
      monthlySeries: [8, 10, 11, 12, 14, 16, 18, 20, 21, 23, 24, 25],
      userStats: { downloads: '45K visitors', users: '12K', rating: '4.7', retention: '62%' },
      cover: 'travel',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-12T00:00:00.000Z'),
    },
    {
      id: 'study-master',
      type: 'app',
      name: 'Study Master',
      subtitle: 'Complete learning app with mock tests, quizzes and notes',
      titleExtra: 'Study Master – Exam Preparation App',
      category: 'Education',
      price: 40000,
      monthlyRevenue: 8000,
      traffic: '',
      downloads: '50,000+',
      rating: 4.6,
      reviews: 3200,
      appSize: '18 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads (AdMob), In-App Purchases',
      included: 'Source Code, App Store Assets, Documentation',
      support: '1 Month Support',
      lastUpdated: '15 Mar 2024',
      listedOn: '10 Sep 2025',
      description:
        'Study Master is a fully functional Android app for exam preparation. It offers mock tests, quizzes, study notes and current affairs for various competitive exams. The app has a clean and modern UI, strong user base and multiple monetization options. It is ready to be rebranded or further expanded.',
      keyFeatures: [
        '10,000+ practice questions',
        'Mock tests with detailed analysis',
        'Study notes & current affairs',
        'Multiple exam categories (SSC, Banking, Railway etc.)',
        'User-friendly and modern UI',
        'AdMob and in-app purchase integrated',
        'Firebase backend (optional)',
        'Regular content updates',
        'Easy to customize and rebrand',
      ],
      whySelling:
        'I am focusing on a new project in a different niche, so I am looking to sell this app to someone who can take it to the next level.',
      techStack: ['Kotlin', 'Firebase', 'AdMob', 'Android Studio', 'MySQL'],
      monthlySeries: [4, 5, 6, 6, 7, 8, 9, 11, 13, 16, 17, 18],
      userStats: { downloads: '50K+', users: '32K', rating: '4.6', retention: '78%' },
      cover: 'study',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-10T00:00:00.000Z'),
    },
    {
      id: 'recipe-world',
      type: 'website',
      name: 'Recipe World',
      subtitle: 'Good food, great stories',
      category: 'Food & Recipes',
      price: 75000,
      monthlyRevenue: 15000,
      traffic: '30K',
      downloads: '',
      rating: 4.5,
      reviews: 40,
      appSize: '',
      domainAge: '1.5 Years',
      minAndroid: '',
      language: 'English, Hindi',
      monetization: 'AdSense, Affiliates',
      included: 'Domain, Recipes, Email list',
      support: '2 Weeks Support',
      lastUpdated: '01 Sep 2025',
      listedOn: '08 Sep 2025',
      description: 'Hindi + English recipe blog with Google AdSense and affiliate kitchen-gear links.',
      keyFeatures: ['340 evergreen posts', 'Email list of 4,200 cooks', 'Bilingual content'],
      whySelling: 'Need capital for a cloud kitchen brand.',
      techStack: ['WordPress', 'PHP', 'MySQL'],
      monthlySeries: [6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 14, 15],
      userStats: { downloads: '30K visitors', users: '8K', rating: '4.5', retention: '55%' },
      cover: 'food',
      sellerId: anand.id,
      status: 'pending',
      featured: false,
      createdAt: listed('2025-09-08T00:00:00.000Z'),
    },
    {
      id: 'ludo-star',
      type: 'app',
      name: 'Ludo Star',
      subtitle: 'Classic ludo with online rooms',
      category: 'Games',
      price: 120000,
      monthlyRevenue: 22000,
      traffic: '',
      downloads: '500K+',
      rating: 4.4,
      reviews: 18000,
      appSize: '25 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads, Coins IAP',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '20 Aug 2025',
      listedOn: '01 Sep 2025',
      description: 'Online ludo with private rooms, coins and festive boards. High download base in India.',
      keyFeatures: ['Online multiplayer', 'Private rooms', 'Coin store', 'Festive skins'],
      whySelling: 'Deal already in progress with a gaming studio.',
      techStack: ['Unity', 'Photon', 'AdMob'],
      monthlySeries: [10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22],
      userStats: { downloads: '500K+', users: '80K', rating: '4.4', retention: '41%' },
      cover: 'ludo',
      sellerId: anand.id,
      status: 'sold',
      featured: false,
      createdAt: listed('2025-09-01T00:00:00.000Z'),
    },
    {
      id: 'greenkart-store',
      type: 'website',
      name: 'GreenKart Store',
      subtitle: 'Bring nature home',
      category: 'E-commerce',
      price: 90000,
      monthlyRevenue: 18000,
      traffic: '28K',
      downloads: '',
      rating: 4.6,
      reviews: 52,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: 'Product sales',
      included: 'Store, Product catalog, Brand assets',
      support: '2 Weeks Support',
      lastUpdated: '22 Aug 2025',
      listedOn: '28 Aug 2025',
      description: 'Indoor plants ecommerce store with Shopify catalog and UPI checkout.',
      keyFeatures: ['Ready catalog', 'UPI checkout', 'Care guides'],
      whySelling: 'Founder moving abroad.',
      techStack: ['Shopify', 'Liquid'],
      monthlySeries: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18],
      userStats: { downloads: '28K visitors', users: '6K', rating: '4.6', retention: '48%' },
      cover: 'plants',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-28T00:00:00.000Z'),
    },
    {
      id: 'expense-tracker',
      type: 'app',
      name: 'Expense Tracker',
      subtitle: 'Personal finance with UPI SMS parsing',
      category: 'Finance',
      price: 45000,
      monthlyRevenue: 5000,
      traffic: '',
      downloads: '100K+',
      rating: 4.7,
      reviews: 4100,
      appSize: '12 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Freemium, Cloud backup',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '12 Aug 2025',
      listedOn: '20 Aug 2025',
      description: 'Personal expense tracker with UPI SMS parsing and monthly reports.',
      keyFeatures: ['UPI SMS parse', 'Budgets', 'Cloud backup'],
      whySelling: 'Building a B2B finance suite.',
      techStack: ['Flutter', 'Firebase'],
      monthlySeries: [2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5],
      userStats: { downloads: '100K+', users: '22K', rating: '4.7', retention: '71%' },
      cover: 'finance',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-20T00:00:00.000Z'),
    },
    {
      id: 'study-master-anand',
      type: 'app',
      name: 'Study Master',
      subtitle: 'Complete learning app with mock tests, quizzes and notes',
      titleExtra: 'Study Master – Exam Preparation App',
      category: 'Education',
      price: 40000,
      monthlyRevenue: 8000,
      traffic: '',
      downloads: '50K+',
      rating: 4.6,
      reviews: 3200,
      appSize: '18 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads (AdMob), In-App Purchases',
      included: 'Source Code, App Store Assets, Documentation',
      support: '1 Month Support',
      lastUpdated: '15 Mar 2024',
      listedOn: '10 Sep 2025',
      description:
        'Study Master is a fully functional Android app for exam preparation. It offers mock tests, quizzes, study notes and current affairs for various competitive exams.',
      keyFeatures: [
        '10,000+ practice questions',
        'Mock tests with detailed analysis',
        'Study notes & current affairs',
      ],
      whySelling: 'Focusing on a new niche.',
      techStack: ['Kotlin', 'Firebase', 'AdMob'],
      monthlySeries: [4, 5, 6, 6, 7, 8, 9, 11, 13, 16, 17, 18],
      userStats: { downloads: '50K+', users: '32K', rating: '4.6', retention: '78%' },
      cover: 'study',
      sellerId: anand.id,
      status: 'approved',
      featured: false,
      hiddenPublic: true,
      createdAt: listed('2025-09-10T00:00:00.000Z'),
    },
    {
      id: 'exam-prep-pro',
      type: 'app',
      name: 'Exam Prep Pro',
      subtitle: 'Banking and SSC mock tests',
      category: 'Education',
      price: 35000,
      monthlyRevenue: 4200,
      traffic: '',
      downloads: '22K+',
      rating: 4.5,
      reviews: 900,
      appSize: '16 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads, IAP',
      included: 'Source Code',
      support: '2 Weeks Support',
      lastUpdated: '10 Jan 2025',
      listedOn: '02 Aug 2025',
      description: 'Focused mock-test app for banking and SSC aspirants.',
      keyFeatures: ['Sectional tests', 'Rank prediction'],
      whySelling: 'Portfolio cleanup.',
      techStack: ['Kotlin', 'Firebase'],
      monthlySeries: [2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4],
      userStats: { downloads: '22K+', users: '9K', rating: '4.5', retention: '66%' },
      cover: 'exam',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-08-02T00:00:00.000Z'),
    },
    {
      id: 'current-affairs-daily',
      type: 'app',
      name: 'Current Affairs Daily',
      subtitle: 'News & Magazines',
      category: 'News & Magazines',
      price: 28000,
      monthlyRevenue: 3100,
      traffic: '',
      downloads: '40K+',
      rating: 4.3,
      reviews: 1200,
      appSize: '10 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads',
      included: 'Source Code',
      support: '2 Weeks Support',
      lastUpdated: '01 Feb 2025',
      listedOn: '20 Jul 2025',
      description: 'Daily current affairs capsules for competitive exams.',
      keyFeatures: ['Daily quiz', 'PDF capsules'],
      whySelling: 'Time constraints.',
      techStack: ['Flutter', 'Firebase'],
      monthlySeries: [2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      userStats: { downloads: '40K+', users: '11K', rating: '4.3', retention: '60%' },
      cover: 'news',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-07-20T00:00:00.000Z'),
    },
    {
      id: 'math-solver',
      type: 'app',
      name: 'Math Solver',
      subtitle: 'Step by step solutions',
      category: 'Education',
      price: 50000,
      monthlyRevenue: 6700,
      traffic: '',
      downloads: '80K+',
      rating: 4.6,
      reviews: 5400,
      appSize: '22 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Ads, Premium',
      included: 'Source Code',
      support: '1 Month Support',
      lastUpdated: '08 Mar 2025',
      listedOn: '11 Jul 2025',
      description: 'Camera math solver with step-by-step explanations.',
      keyFeatures: ['Camera input', 'Steps', 'Offline mode'],
      whySelling: 'Team moving to web.',
      techStack: ['Flutter', 'TensorFlow Lite'],
      monthlySeries: [3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7],
      userStats: { downloads: '80K+', users: '19K', rating: '4.6', retention: '69%' },
      cover: 'math',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-07-11T00:00:00.000Z'),
    },
    {
      id: 'gk-master',
      type: 'app',
      name: 'GK Master',
      subtitle: 'General knowledge drills',
      category: 'Education',
      price: 30000,
      monthlyRevenue: 2900,
      traffic: '',
      downloads: '35K+',
      rating: 4.4,
      reviews: 800,
      appSize: '14 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads',
      included: 'Source Code',
      support: '2 Weeks Support',
      lastUpdated: '19 Apr 2025',
      listedOn: '01 Jul 2025',
      description: 'GK quizzes for UPSC prelims and state PSC.',
      keyFeatures: ['Daily GK', 'Yearbook pack'],
      whySelling: 'Content team left.',
      techStack: ['Kotlin', 'Room'],
      monthlySeries: [1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3],
      userStats: { downloads: '35K+', users: '8K', rating: '4.4', retention: '58%' },
      cover: 'gk',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-07-01T00:00:00.000Z'),
    },
    {
      id: 'pdf-tools-pro',
      type: 'website',
      name: 'PDF Tools Pro',
      subtitle: 'Merge, compress and e-sign PDFs',
      category: 'Tools & Utilities',
      price: 45000,
      monthlyRevenue: 8000,
      traffic: '12K',
      downloads: '',
      rating: 4.5,
      reviews: 30,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: 'SaaS plans',
      included: 'Codebase, Stripe/Razorpay',
      support: '2 Weeks Support',
      lastUpdated: '01 Sep 2025',
      listedOn: '05 Sep 2025',
      description: 'Online PDF merge, compress, and e-sign toolkit used by Indian SMEs.',
      keyFeatures: ['Merge', 'Compress', 'eSign'],
      whySelling: 'Side project.',
      techStack: ['React', 'Node.js', 'MongoDB'],
      monthlySeries: [4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8],
      userStats: { downloads: '12K visitors', users: '180 shops', rating: '4.5', retention: '70%' },
      cover: 'pdf',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-05T00:00:00.000Z'),
    }
  );

  offers.push(
    {
      id: uuid(),
      listingId: 'travel-guide-blog',
      buyerId: arjun.id,
      sellerId: anand.id,
      amount: 110000,
      message: 'Can we close this week?',
      status: 'open',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuid(),
      listingId: 'study-master',
      buyerId: arjun.id,
      sellerId: rahul.id,
      amount: 36000,
      message: 'Offer for Play transfer + source.',
      status: 'open',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuid(),
      listingId: 'greenkart-store',
      buyerId: arjun.id,
      sellerId: anand.id,
      amount: 82000,
      message: 'Interested if plants inventory is included.',
      status: 'open',
      createdAt: new Date().toISOString(),
    }
  );

  messages.push(
    {
      id: uuid(),
      listingId: 'travel-guide-blog',
      fromId: arjun.id,
      toId: anand.id,
      text: 'Is the domain included in the asking price?',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuid(),
      listingId: 'expense-tracker',
      fromId: arjun.id,
      toId: anand.id,
      text: 'Can you share last 6 months Play Console?',
      createdAt: new Date().toISOString(),
    }
  );
}

module.exports = { users, listings, offers, messages, watchlist, seed };
