const { v4: uuid } = require('uuid');

const users = [];
const listings = [];
const offers = [];
const messages = [];
const watchlist = [];

function seed() {
  if (users.length) return;

  const admin = {
    id: uuid(),
    name: 'Admin',
    email: 'admin@nexmarket.in',
    password: 'admin123',
    role: 'admin',
    verified: true,
    createdAt: '2022-01-10T00:00:00.000Z',
  };
  const anand = {
    id: uuid(),
    name: 'Anand Sharma',
    email: 'anand@seller.in',
    password: 'seller123',
    role: 'user',
    verified: true,
    rating: 4.9,
    reviews: 18,
    earnings: 285000,
    createdAt: '2022-01-15T00:00:00.000Z',
  };
  const rahul = {
    id: uuid(),
    name: 'Rahul Kumar',
    email: 'rahul@seller.in',
    password: 'seller123',
    role: 'user',
    verified: true,
    rating: 4.8,
    reviews: 24,
    earnings: 0,
    createdAt: '2022-01-01T00:00:00.000Z',
  };
  const ravi = {
    id: uuid(),
    name: 'Ravi Singh',
    email: 'ravi@seller.in',
    password: 'seller123',
    role: 'user',
    verified: true,
    rating: 4.7,
    reviews: 9,
    earnings: 0,
    createdAt: '2023-03-01T00:00:00.000Z',
  };
  const arjun = {
    id: uuid(),
    name: 'Arjun Mehta',
    email: 'arjun@buyer.in',
    password: 'buyer123',
    role: 'user',
    verified: false,
    createdAt: new Date().toISOString(),
  };
  users.push(admin, anand, rahul, ravi, arjun);

  const listed = (d) => d;

  listings.push(
    {
      id: 'travel-guide-blog',
      type: 'website',
      name: 'Travel Guide Blog',
      subtitle: 'Explore the world with destination guides',
      category: 'Travel & Lifestyle',
      price: 120000,
      monthlyRevenue: 25000,
      traffic: '45K',
      platform: 'WordPress',
      downloads: '',
      rating: 4.7,
      reviews: 86,
      appSize: '',
      domainAge: '2 Years',
      minAndroid: '',
      language: 'English',
      monetization: 'Ads, Affiliates',
      included: 'Domain, Hosting setup, Content, Analytics',
      support: '2 Weeks Support',
      lastUpdated: '02 Sep 2025',
      listedOn: '12 Sep 2025',
      description:
        'India-first travel magazine with destination guides, affiliate hotel bookings and a growing email list. Strong SEO for hill-station and weekend-getaway queries.',
      keyFeatures: [
        'Evergreen destination guides',
        'Affiliate hotel and tour widgets',
        'Email list of 18,000 readers',
        'Clean WordPress theme',
      ],
      whySelling: 'Moving focus to a SaaS product and want a travel publisher to scale this brand.',
      techStack: ['WordPress', 'PHP', 'MySQL'],
      monthlySeries: [8, 10, 11, 12, 14, 16, 18, 20, 21, 23, 24, 25],
      userStats: { downloads: '45K visitors', users: '12K', rating: '4.7', retention: '62%' },
      cover: 'travel',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-12T00:00:00.000Z'),
    },
    {
      id: 'study-master',
      type: 'app',
      name: 'Study Master',
      subtitle: 'Complete learning app with mock tests, quizzes and notes',
      titleExtra: 'Study Master – Exam Preparation App',
      category: 'Education',
      price: 40000,
      monthlyRevenue: 8000,
      traffic: '',
      downloads: '50,000+',
      rating: 4.6,
      reviews: 3200,
      appSize: '18 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads (AdMob), In-App Purchases',
      included: 'Source Code, App Store Assets, Documentation',
      support: '1 Month Support',
      lastUpdated: '15 Mar 2024',
      listedOn: '10 Sep 2025',
      description:
        'Study Master is a fully functional Android app for exam preparation. It offers mock tests, quizzes, study notes and current affairs for various competitive exams. The app has a clean and modern UI, strong user base and multiple monetization options. It is ready to be rebranded or further expanded.',
      keyFeatures: [
        '10,000+ practice questions',
        'Mock tests with detailed analysis',
        'Study notes & current affairs',
        'Multiple exam categories (SSC, Banking, Railway etc.)',
        'User-friendly and modern UI',
        'AdMob and in-app purchase integrated',
        'Firebase backend (optional)',
        'Regular content updates',
        'Easy to customize and rebrand',
      ],
      whySelling:
        'I am focusing on a new project in a different niche, so I am looking to sell this app to someone who can take it to the next level.',
      techStack: ['Kotlin', 'Firebase', 'AdMob', 'Android Studio', 'MySQL'],
      monthlySeries: [4, 5, 6, 6, 7, 8, 9, 11, 13, 16, 17, 18],
      userStats: { downloads: '50K+', users: '32K', rating: '4.6', retention: '78%' },
      cover: 'study',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-10T00:00:00.000Z'),
    },
    {
      id: 'recipe-world',
      type: 'website',
      name: 'Recipe World',
      subtitle: 'Good food, great stories',
      category: 'Food & Recipes',
      price: 75000,
      monthlyRevenue: 15000,
      traffic: '30K',
      downloads: '',
      rating: 4.5,
      reviews: 40,
      appSize: '',
      domainAge: '1.5 Years',
      minAndroid: '',
      language: 'English, Hindi',
      monetization: 'Ads, Affiliates',
      platform: 'WordPress',
      included: 'Domain, Recipes, Email list',
      support: '2 Weeks Support',
      lastUpdated: '01 Sep 2025',
      listedOn: '08 Sep 2025',
      description: 'Hindi + English recipe blog with Google AdSense and affiliate kitchen-gear links.',
      keyFeatures: ['340 evergreen posts', 'Email list of 4,200 cooks', 'Bilingual content'],
      whySelling: 'Need capital for a cloud kitchen brand.',
      techStack: ['WordPress', 'PHP', 'MySQL'],
      monthlySeries: [6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 14, 15],
      userStats: { downloads: '30K visitors', users: '8K', rating: '4.5', retention: '55%' },
      cover: 'food',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-08T00:00:00.000Z'),
    },
    {
      id: 'ludo-star',
      type: 'app',
      name: 'Ludo Star',
      subtitle: 'Classic ludo with online rooms',
      category: 'Games',
      price: 120000,
      monthlyRevenue: 25000,
      traffic: '',
      downloads: '500K+',
      rating: 4.4,
      reviews: 18000,
      appSize: '25 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads, Coins IAP',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '20 Aug 2025',
      listedOn: '01 Sep 2025',
      description: 'Online ludo with private rooms, coins and festive boards. High download base in India.',
      keyFeatures: ['Online multiplayer', 'Private rooms', 'Coin store', 'Festive skins'],
      whySelling: 'Deal already in progress with a gaming studio.',
      techStack: ['Unity', 'Photon', 'AdMob'],
      monthlySeries: [10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22],
      userStats: { downloads: '500K+', users: '80K', rating: '4.4', retention: '41%' },
      cover: 'ludo',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-01T00:00:00.000Z'),
    },
    {
      id: 'greenkart-store',
      type: 'website',
      name: 'GreenKart Store',
      subtitle: 'Bring nature home',
      category: 'E-commerce',
      price: 90000,
      monthlyRevenue: 18000,
      traffic: '28K',
      platform: 'Shopify',
      downloads: '',
      rating: 4.6,
      reviews: 52,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: 'Product sales',
      included: 'Store, Product catalog, Brand assets',
      support: '2 Weeks Support',
      lastUpdated: '22 Aug 2025',
      listedOn: '28 Aug 2025',
      description: 'Indoor plants ecommerce store with Shopify catalog and UPI checkout.',
      keyFeatures: ['Ready catalog', 'UPI checkout', 'Care guides'],
      whySelling: 'Founder moving abroad.',
      techStack: ['Shopify', 'Liquid'],
      monthlySeries: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18],
      userStats: { downloads: '28K visitors', users: '6K', rating: '4.6', retention: '48%' },
      cover: 'plants',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-28T00:00:00.000Z'),
    },
    {
      id: 'expense-tracker',
      type: 'app',
      name: 'Expense Tracker',
      subtitle: 'Personal finance with UPI SMS parsing',
      category: 'Finance',
      price: 75000,
      monthlyRevenue: 15000,
      traffic: '',
      downloads: '100K+',
      rating: 4.7,
      reviews: 4100,
      appSize: '12 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Freemium, Cloud backup',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '12 Aug 2025',
      listedOn: '20 Aug 2025',
      description: 'Personal expense tracker with UPI SMS parsing and monthly reports.',
      keyFeatures: ['UPI SMS parse', 'Budgets', 'Cloud backup'],
      whySelling: 'Building a B2B finance suite.',
      techStack: ['Flutter', 'Firebase'],
      monthlySeries: [2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5],
      userStats: { downloads: '100K+', users: '22K', rating: '4.7', retention: '71%' },
      cover: 'finance',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-20T00:00:00.000Z'),
    },
    {
      id: 'study-master-anand',
      type: 'app',
      name: 'Study Master',
      subtitle: 'Complete learning app with mock tests, quizzes and notes',
      titleExtra: 'Study Master – Exam Preparation App',
      category: 'Education',
      price: 40000,
      monthlyRevenue: 8000,
      traffic: '',
      downloads: '50K+',
      rating: 4.6,
      reviews: 3200,
      appSize: '18 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads (AdMob), In-App Purchases',
      included: 'Source Code, App Store Assets, Documentation',
      support: '1 Month Support',
      lastUpdated: '15 Mar 2024',
      listedOn: '10 Sep 2025',
      description:
        'Study Master is a fully functional Android app for exam preparation. It offers mock tests, quizzes, study notes and current affairs for various competitive exams.',
      keyFeatures: [
        '10,000+ practice questions',
        'Mock tests with detailed analysis',
        'Study notes & current affairs',
      ],
      whySelling: 'Focusing on a new niche.',
      techStack: ['Kotlin', 'Firebase', 'AdMob'],
      monthlySeries: [4, 5, 6, 6, 7, 8, 9, 11, 13, 16, 17, 18],
      userStats: { downloads: '50K+', users: '32K', rating: '4.6', retention: '78%' },
      cover: 'study',
      sellerId: anand.id,
      status: 'approved',
      featured: false,
      hiddenPublic: true,
      createdAt: listed('2025-09-10T00:00:00.000Z'),
    },
    {
      id: 'exam-prep-pro',
      type: 'app',
      name: 'Exam Prep Pro',
      subtitle: 'Banking and SSC mock tests',
      category: 'Education',
      price: 35000,
      monthlyRevenue: 4200,
      traffic: '',
      downloads: '22K+',
      rating: 4.5,
      reviews: 900,
      appSize: '16 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads, IAP',
      included: 'Source Code',
      support: '2 Weeks Support',
      lastUpdated: '10 Jan 2025',
      listedOn: '02 Aug 2025',
      description: 'Focused mock-test app for banking and SSC aspirants.',
      keyFeatures: ['Sectional tests', 'Rank prediction'],
      whySelling: 'Portfolio cleanup.',
      techStack: ['Kotlin', 'Firebase'],
      monthlySeries: [2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4],
      userStats: { downloads: '22K+', users: '9K', rating: '4.5', retention: '66%' },
      cover: 'exam',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-08-02T00:00:00.000Z'),
    },
    {
      id: 'current-affairs-daily',
      type: 'app',
      name: 'Current Affairs Daily',
      subtitle: 'News & Magazines',
      category: 'News & Magazines',
      price: 28000,
      monthlyRevenue: 3100,
      traffic: '',
      downloads: '40K+',
      rating: 4.3,
      reviews: 1200,
      appSize: '10 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads',
      included: 'Source Code',
      support: '2 Weeks Support',
      lastUpdated: '01 Feb 2025',
      listedOn: '20 Jul 2025',
      description: 'Daily current affairs capsules for competitive exams.',
      keyFeatures: ['Daily quiz', 'PDF capsules'],
      whySelling: 'Time constraints.',
      techStack: ['Flutter', 'Firebase'],
      monthlySeries: [2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      userStats: { downloads: '40K+', users: '11K', rating: '4.3', retention: '60%' },
      cover: 'news',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-07-20T00:00:00.000Z'),
    },
    {
      id: 'math-solver',
      type: 'app',
      name: 'Math Solver',
      subtitle: 'Step by step solutions',
      category: 'Education',
      price: 50000,
      monthlyRevenue: 6700,
      traffic: '',
      downloads: '80K+',
      rating: 4.6,
      reviews: 5400,
      appSize: '22 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Ads, Premium',
      included: 'Source Code',
      support: '1 Month Support',
      lastUpdated: '08 Mar 2025',
      listedOn: '11 Jul 2025',
      description: 'Camera math solver with step-by-step explanations.',
      keyFeatures: ['Camera input', 'Steps', 'Offline mode'],
      whySelling: 'Team moving to web.',
      techStack: ['Flutter', 'TensorFlow Lite'],
      monthlySeries: [3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7],
      userStats: { downloads: '80K+', users: '19K', rating: '4.6', retention: '69%' },
      cover: 'math',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-07-11T00:00:00.000Z'),
    },
    {
      id: 'gk-master',
      type: 'app',
      name: 'GK Master',
      subtitle: 'General knowledge drills',
      category: 'Education',
      price: 30000,
      monthlyRevenue: 2900,
      traffic: '',
      downloads: '35K+',
      rating: 4.4,
      reviews: 800,
      appSize: '14 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads',
      included: 'Source Code',
      support: '2 Weeks Support',
      lastUpdated: '19 Apr 2025',
      listedOn: '01 Jul 2025',
      description: 'GK quizzes for UPSC prelims and state PSC.',
      keyFeatures: ['Daily GK', 'Yearbook pack'],
      whySelling: 'Content team left.',
      techStack: ['Kotlin', 'Room'],
      monthlySeries: [1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3],
      userStats: { downloads: '35K+', users: '8K', rating: '4.4', retention: '58%' },
      cover: 'gk',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-07-01T00:00:00.000Z'),
    },
    {
      id: 'pdf-tools-pro',
      type: 'website',
      name: 'TaskFlow Pro',
      subtitle: 'Make productivity simple for teams',
      category: 'Tools & Utilities',
      price: 45000,
      monthlyRevenue: 8000,
      traffic: '12K',
      downloads: '',
      rating: 4.5,
      reviews: 30,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: 'SaaS plans',
      platform: 'Custom',
      included: 'Codebase, Stripe/Razorpay',
      support: '2 Weeks Support',
      lastUpdated: '01 Sep 2025',
      listedOn: '05 Sep 2025',
      description: 'Team productivity workspace with boards, docs and lightweight automation used by Indian SMEs.',
      keyFeatures: ['Kanban boards', 'Docs', 'Automations'],
      whySelling: 'Side project.',
      techStack: ['React', 'Node.js', 'MongoDB'],
      monthlySeries: [4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8],
      userStats: { downloads: '12K visitors', users: '180 shops', rating: '4.5', retention: '70%' },
      cover: 'taskflow',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-05T00:00:00.000Z'),
    },
    {
      id: 'aitify-hub',
      type: 'website',
      name: 'Aitify Hub',
      subtitle: 'AI tools for everyone',
      category: 'Technology',
      price: 150000,
      monthlyRevenue: 32000,
      traffic: '60K',
      downloads: '',
      rating: 4.8,
      reviews: 64,
      appSize: '',
      domainAge: '2 Years',
      minAndroid: '',
      language: 'English',
      monetization: 'SaaS, Ads',
      platform: 'Custom',
      included: 'Codebase, Brand, User base',
      support: '1 Month Support',
      lastUpdated: '04 Sep 2025',
      listedOn: '11 Sep 2025',
      description: 'Directory of AI writing, image and automation tools with paid listings and affiliate commissions.',
      keyFeatures: ['Tool directory', 'Paid placements', 'Newsletter'],
      whySelling: 'Founder joining an AI startup.',
      techStack: ['Next.js', 'Node.js', 'PostgreSQL'],
      monthlySeries: [12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 31, 32],
      userStats: { downloads: '60K visitors', users: '9K', rating: '4.8', retention: '58%' },
      cover: 'aitify',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-11T00:00:00.000Z'),
    },
    {
      id: 'news-portal',
      type: 'website',
      name: 'News Portal',
      subtitle: 'Daily news trusted and updated',
      category: 'News & Media',
      price: 250000,
      monthlyRevenue: 45000,
      traffic: '100K',
      downloads: '',
      rating: 4.6,
      reviews: 120,
      appSize: '',
      domainAge: '4 Years',
      minAndroid: '',
      language: 'English, Hindi',
      monetization: 'Ads, Affiliates',
      platform: 'WordPress',
      included: 'Domain, CMS, Ad slots',
      support: '2 Weeks Support',
      lastUpdated: '06 Sep 2025',
      listedOn: '09 Sep 2025',
      description: 'India news portal covering politics, business and cricket with a large returning audience.',
      keyFeatures: ['Breaking news desk', 'Ad network', 'Newsletter'],
      whySelling: 'Media group consolidation.',
      techStack: ['WordPress', 'PHP', 'MySQL'],
      monthlySeries: [20, 22, 25, 28, 30, 32, 34, 36, 38, 40, 43, 45],
      userStats: { downloads: '100K visitors', users: '28K', rating: '4.6', retention: '44%' },
      cover: 'newsportal',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-09T00:00:00.000Z'),
    },
    {
      id: 'studynest',
      type: 'website',
      name: 'StudyNest',
      subtitle: 'Learn without limits',
      category: 'Education',
      price: 60000,
      monthlyRevenue: 12000,
      traffic: '25K',
      downloads: '',
      rating: 4.5,
      reviews: 38,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: 'Courses, Ads',
      platform: 'Custom',
      included: 'Course catalog, LMS',
      support: '2 Weeks Support',
      lastUpdated: '28 Aug 2025',
      listedOn: '03 Sep 2025',
      description: 'Online learning site with recorded classes for class 10-12 and entrance exams.',
      keyFeatures: ['Recorded classes', 'Notes PDFs', 'Live doubt chat'],
      whySelling: 'Moving to offline coaching.',
      techStack: ['React', 'Django', 'PostgreSQL'],
      monthlySeries: [5, 6, 7, 8, 8, 9, 10, 10, 11, 11, 12, 12],
      userStats: { downloads: '25K visitors', users: '4K', rating: '4.5', retention: '61%' },
      cover: 'studynest',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-03T00:00:00.000Z'),
    },
    {
      id: 'finflow-blog',
      type: 'website',
      name: 'FinFlow Blog',
      subtitle: 'Smarter financial decisions',
      category: 'Finance',
      price: 100000,
      monthlyRevenue: 20000,
      traffic: '40K',
      downloads: '',
      rating: 4.7,
      reviews: 55,
      appSize: '',
      domainAge: '3 Years',
      minAndroid: '',
      language: 'English',
      monetization: 'Ads, Affiliates',
      platform: 'WordPress',
      included: 'Domain, Content archive',
      support: '2 Weeks Support',
      lastUpdated: '30 Aug 2025',
      listedOn: '04 Sep 2025',
      description: 'Personal finance blog covering mutual funds, credit cards and tax planning for Indian readers.',
      keyFeatures: ['Evergreen guides', 'Affiliate cards', 'Email list'],
      whySelling: 'Owner joining a fintech.',
      techStack: ['WordPress', 'PHP', 'MySQL'],
      monthlySeries: [8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20],
      userStats: { downloads: '40K visitors', users: '11K', rating: '4.7', retention: '52%' },
      cover: 'finflow',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-04T00:00:00.000Z'),
    },
    {
      id: 'habit-tracker-pro',
      type: 'app',
      name: 'Habit Tracker Pro',
      subtitle: 'Build better routines every day',
      category: 'Health & Fitness',
      price: 50000,
      monthlyRevenue: 12000,
      traffic: '',
      downloads: '100K+',
      rating: 4.8,
      reviews: 8600,
      appSize: '14 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Freemium, IAP',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '18 Aug 2025',
      listedOn: '02 Sep 2025',
      description: 'Habit streaks, reminders and wellness reports with a loyal daily-active user base.',
      keyFeatures: ['Streaks', 'Reminders', 'Insights'],
      whySelling: 'Team shifting to wearables.',
      techStack: ['Flutter', 'Firebase'],
      monthlySeries: [6, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12],
      userStats: { downloads: '100K+', users: '28K', rating: '4.8', retention: '74%' },
      cover: 'habit',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-09-02T00:00:00.000Z'),
    },
    {
      id: 'photo-editor-pro',
      type: 'app',
      name: 'Photo Editor Pro',
      subtitle: 'Filters, portraits and collages',
      category: 'Photography',
      price: 45000,
      monthlyRevenue: 10000,
      traffic: '',
      downloads: '50K+',
      rating: 4.5,
      reviews: 2100,
      appSize: '28 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Ads, Pro unlock',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '12 Aug 2025',
      listedOn: '25 Aug 2025',
      description: 'Portrait retouch, filters and collage maker popular with creators on Play Store.',
      keyFeatures: ['Filters', 'Collage', 'Retouch'],
      whySelling: 'Focusing on a camera hardware kit.',
      techStack: ['Kotlin', 'OpenGL'],
      monthlySeries: [4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10],
      userStats: { downloads: '50K+', users: '14K', rating: '4.5', retention: '49%' },
      cover: 'photo',
      sellerId: rahul.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-25T00:00:00.000Z'),
    },
    {
      id: 'weather-live',
      type: 'app',
      name: 'Weather Live',
      subtitle: 'Hyperlocal weather and radar',
      category: 'Weather',
      price: 35000,
      monthlyRevenue: 8000,
      traffic: '',
      downloads: '100K+',
      rating: 4.6,
      reviews: 5400,
      appSize: '11 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads, Premium',
      included: 'Source Code, Play assets',
      support: '2 Weeks Support',
      lastUpdated: '05 Aug 2025',
      listedOn: '18 Aug 2025',
      description: 'Live weather, hourly forecasts and rain alerts for Indian cities.',
      keyFeatures: ['Hourly forecast', 'Rain alerts', 'Widgets'],
      whySelling: 'API costs rising.',
      techStack: ['Flutter', 'OpenWeather'],
      monthlySeries: [3, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8],
      userStats: { downloads: '100K+', users: '21K', rating: '4.6', retention: '63%' },
      cover: 'weather',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-18T00:00:00.000Z'),
    },
    {
      id: 'recipe-book',
      type: 'app',
      name: 'Recipe Book',
      subtitle: 'Indian recipes with meal plans',
      category: 'Food & Drink',
      price: 28000,
      monthlyRevenue: 5000,
      traffic: '',
      downloads: '50K+',
      rating: 4.3,
      reviews: 1900,
      appSize: '20 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English, Hindi',
      monetization: 'Ads, Cookbook IAP',
      included: 'Source Code, Play assets',
      support: '2 Weeks Support',
      lastUpdated: '01 Aug 2025',
      listedOn: '12 Aug 2025',
      description: 'Home-style Indian recipes with grocery lists and weekly meal plans.',
      keyFeatures: ['Recipes', 'Meal plans', 'Grocery list'],
      whySelling: 'Owner launching a kitchen brand.',
      techStack: ['Kotlin', 'Firebase'],
      monthlySeries: [2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5],
      userStats: { downloads: '50K+', users: '12K', rating: '4.3', retention: '57%' },
      cover: 'recipebook',
      sellerId: rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed('2025-08-12T00:00:00.000Z'),
    },
    {
      id: 'daily-planner',
      type: 'app',
      name: 'Daily Planner',
      subtitle: 'Tasks, calendar and focus timer',
      category: 'Productivity',
      price: 42000,
      monthlyRevenue: 10000,
      traffic: '',
      downloads: '100K+',
      rating: 4.7,
      reviews: 4300,
      appSize: '16 MB',
      domainAge: '',
      minAndroid: 'Android 6.0+',
      language: 'English',
      monetization: 'Freemium, Cloud sync',
      included: 'Source Code, Play assets',
      support: '1 Month Support',
      lastUpdated: '22 Aug 2025',
      listedOn: '29 Aug 2025',
      description: 'Daily planner with tasks, calendar and a pomodoro focus timer.',
      keyFeatures: ['Tasks', 'Calendar', 'Focus timer'],
      whySelling: 'Switching to a B2B productivity suite.',
      techStack: ['Flutter', 'Firebase'],
      monthlySeries: [4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10],
      userStats: { downloads: '100K+', users: '19K', rating: '4.7', retention: '68%' },
      cover: 'planner',
      sellerId: anand.id,
      status: 'approved',
      featured: true,
      createdAt: listed('2025-08-29T00:00:00.000Z'),
    }
  );

  const webFill = [
    ['BlogKit', 'Blog', 'WordPress', 18, 6, 38000],
    ['EduNotes Hub', 'Education', 'Custom', 22, 9, 52000],
    ['FitLife Portal', 'Health & Fitness', 'Webflow', 16, 5, 34000],
    ['ShopMini', 'E-commerce', 'Shopify', 33, 14, 82000],
    ['MoneyBrief', 'Finance', 'WordPress', 27, 11, 64000],
    ['CityBytes', 'News & Media', 'WordPress', 48, 17, 110000],
    ['UtilityBox', 'Tools & Utilities', 'Custom', 14, 4, 29000],
    ['Trek Tales', 'Travel & Lifestyle', 'WordPress', 21, 8, 47000],
    ['Spice Bowl', 'Food & Recipes', 'WordPress', 19, 7, 41000],
    ['CodeBazaar', 'Technology', 'Custom', 36, 15, 98000],
    ['Local Classifieds', 'Other', 'Custom', 12, 3, 24000],
    ['Yoga Daily', 'Health & Fitness', 'Webflow', 15, 5, 31000],
  ];
  const appFill = [
    ['Focus Timer', 'Productivity', '80K+', 4.4, 9000, 36000],
    ['Budget Buddy', 'Finance', '60K+', 4.5, 7000, 33000],
    ['Kids Stories', 'Education', '40K+', 4.2, 4000, 22000],
    ['Clip Maker', 'Entertainment', '70K+', 4.3, 8000, 39000],
    ['Home Decor', 'Lifestyle', '30K+', 4.1, 3500, 21000],
    ['CRM Lite', 'Business', '20K+', 4.4, 11000, 54000],
    ['Nearby Events', 'Social', '55K+', 4.2, 6000, 28000],
    ['Cab Compare', 'Travel & Local', '90K+', 4.5, 13000, 61000],
    ['QR Toolkit', 'Tools', '120K+', 4.6, 8500, 37000],
    ['Puzzle Box', 'Games', '200K+', 4.3, 16000, 72000],
    ['Salon Book', 'Lifestyle', '25K+', 4.0, 3200, 19000],
    ['Invoice Pro', 'Business', '35K+', 4.5, 14000, 68000],
  ];

  webFill.forEach((row, i) => {
    const [name, category, platform, traffic, revenue, price] = row;
    listings.push({
      id: `web-fill-${i + 1}`,
      type: 'website',
      name,
      subtitle: `${name} digital property`,
      category,
      price: price * 1000 / 1000,
      monthlyRevenue: revenue * 1000,
      traffic: `${traffic}K`,
      downloads: '',
      rating: 4.3,
      reviews: 20 + i,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: i % 2 ? 'Ads, Affiliates' : 'SaaS',
      platform,
      included: 'Domain, Code, Analytics',
      support: '2 Weeks Support',
      lastUpdated: '10 Aug 2025',
      listedOn: '15 Aug 2025',
      description: `${name} is a live ${category.toLowerCase()} website with recurring traffic and revenue.`,
      keyFeatures: ['Ready brand', 'Analytics', 'Monetization'],
      whySelling: 'Portfolio cleanup.',
      techStack: [platform, 'MySQL'],
      monthlySeries: [4, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, revenue],
      userStats: { downloads: `${traffic}K visitors`, users: `${Math.round(traffic / 3)}K`, rating: '4.3', retention: '50%' },
      cover: 'generic',
      sellerId: i % 2 ? anand.id : rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed(`2025-08-${String(10 + (i % 18)).padStart(2, '0')}T00:00:00.000Z`),
    });
  });

  appFill.forEach((row, i) => {
    const [name, category, downloads, rating, revenue, price] = row;
    listings.push({
      id: `app-fill-${i + 1}`,
      type: 'app',
      name,
      subtitle: `${name} Android app`,
      category,
      price,
      monthlyRevenue: revenue,
      traffic: '',
      downloads,
      rating,
      reviews: 400 + i * 20,
      appSize: '15 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads, IAP',
      included: 'Source Code, Play assets',
      support: '2 Weeks Support',
      lastUpdated: '08 Aug 2025',
      listedOn: '16 Aug 2025',
      description: `${name} is a published Android app with an active user base.`,
      keyFeatures: ['Play listing', 'Monetization', 'Source code'],
      whySelling: 'Focusing on a new niche.',
      techStack: ['Kotlin', 'Firebase'],
      monthlySeries: [3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, Math.round(revenue / 1000)],
      userStats: { downloads, users: '8K', rating: String(rating), retention: '55%' },
      cover: 'generic',
      sellerId: i % 2 ? anand.id : rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed(`2025-08-${String(8 + (i % 20)).padStart(2, '0')}T00:00:00.000Z`),
    });
  });

  const extraWebCats = [
    'Tools & Utilities',
    'Blog',
    'E-commerce',
    'News & Media',
    'Education',
    'Finance',
    'Health & Fitness',
    'Travel & Lifestyle',
    'Food & Recipes',
    'Technology',
    'Other',
  ];
  const extraAppCats = [
    'Education',
    'Finance',
    'Health & Fitness',
    'Productivity',
    'Entertainment',
    'Lifestyle',
    'Games',
    'Tools',
    'Business',
    'Social',
    'Travel & Local',
    'Food & Drink',
    'Photography',
    'Weather',
    'Other',
  ];
  const extraWebNames = [
    'LaunchPad',
    'PixelPress',
    'NovaMart',
    'DailyPulse',
    'SkillForge',
    'WealthWire',
    'VitalHub',
    'Wanderly',
    'KitchenLab',
    'Stackly',
    'ClassiBoard',
    'BloomCart',
  ];
  const extraAppNames = [
    'NoteSwift',
    'PayNest',
    'FitLoop',
    'Taskly',
    'Streamlet',
    'CalmBox',
    'ArcadeGo',
    'FixIt',
    'Leadly',
    'CircleUp',
    'TripKit',
    'BiteBook',
    'Lensly',
    'SkyCast',
    'HandyApp',
  ];

  for (let i = 0; i < 108; i += 1) {
    const category = extraWebCats[i % extraWebCats.length];
    const traffic = 8 + (i % 90);
    const revenue = 3 + (i % 28);
    listings.push({
      id: `web-extra-${i + 1}`,
      type: 'website',
      name: `${extraWebNames[i % extraWebNames.length]} ${i + 1}`,
      subtitle: 'Growing digital property',
      category,
      price: 20000 + i * 1500,
      monthlyRevenue: revenue * 1000,
      traffic: `${traffic}K`,
      downloads: '',
      rating: 4 + ((i % 8) / 10),
      reviews: 12 + i,
      appSize: '',
      domainAge: '1 Year',
      minAndroid: '',
      language: 'English',
      monetization: i % 3 === 0 ? 'Ads' : i % 3 === 1 ? 'Affiliates' : 'SaaS',
      platform: i % 2 ? 'WordPress' : 'Custom',
      included: 'Domain, Code, Analytics',
      support: '2 Weeks Support',
      lastUpdated: '12 Jun 2025',
      listedOn: '20 Jun 2025',
      description: `A live ${category.toLowerCase()} website with recurring traffic and revenue.`,
      keyFeatures: ['Ready brand', 'Analytics', 'Monetization'],
      whySelling: 'Portfolio cleanup.',
      techStack: ['WordPress', 'MySQL'],
      monthlySeries: [4, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, revenue],
      userStats: { downloads: `${traffic}K visitors`, users: `${Math.round(traffic / 3)}K`, rating: '4.3', retention: '50%' },
      cover: 'generic',
      sellerId: i % 2 ? anand.id : rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed(`2025-06-${String(1 + (i % 28)).padStart(2, '0')}T00:00:00.000Z`),
    });
  }

  for (let i = 0; i < 72; i += 1) {
    const category = extraAppCats[i % extraAppCats.length];
    const downloads = `${10 + (i % 90)}K+`;
    listings.push({
      id: `app-extra-${i + 1}`,
      type: 'app',
      name: `${extraAppNames[i % extraAppNames.length]} ${i + 1}`,
      subtitle: 'Published Android app',
      category,
      price: 18000 + i * 900,
      monthlyRevenue: 3000 + i * 250,
      traffic: '',
      downloads,
      rating: Number((4 + ((i % 9) / 10)).toFixed(1)),
      reviews: 220 + i * 12,
      appSize: '14 MB',
      domainAge: '',
      minAndroid: 'Android 5.0+',
      language: 'English',
      monetization: 'Ads, IAP',
      included: 'Source Code, Play assets',
      support: '2 Weeks Support',
      lastUpdated: '10 Jun 2025',
      listedOn: '18 Jun 2025',
      description: `A published ${category.toLowerCase()} Android app with an active user base.`,
      keyFeatures: ['Play listing', 'Monetization', 'Source code'],
      whySelling: 'Focusing on a new niche.',
      techStack: ['Kotlin', 'Firebase'],
      monthlySeries: [3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9],
      userStats: { downloads, users: '8K', rating: '4.4', retention: '55%' },
      cover: 'generic',
      sellerId: i % 2 ? anand.id : rahul.id,
      status: 'approved',
      featured: false,
      createdAt: listed(`2025-05-${String(1 + (i % 28)).padStart(2, '0')}T00:00:00.000Z`),
    });
  }

  offers.push(
    {
      id: uuid(),
      listingId: 'travel-guide-blog',
      buyerId: arjun.id,
      sellerId: anand.id,
      amount: 110000,
      message: 'Can we close this week?',
      status: 'open',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuid(),
      listingId: 'study-master',
      buyerId: arjun.id,
      sellerId: rahul.id,
      amount: 36000,
      message: 'Offer for Play transfer + source.',
      status: 'open',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuid(),
      listingId: 'greenkart-store',
      buyerId: arjun.id,
      sellerId: anand.id,
      amount: 82000,
      message: 'Interested if plants inventory is included.',
      status: 'open',
      createdAt: new Date().toISOString(),
    }
  );

  messages.push(
    {
      id: uuid(),
      listingId: 'travel-guide-blog',
      fromId: arjun.id,
      toId: anand.id,
      text: 'Is the domain included in the asking price?',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuid(),
      listingId: 'expense-tracker',
      fromId: arjun.id,
      toId: anand.id,
      text: 'Can you share last 6 months Play Console?',
      createdAt: new Date().toISOString(),
    }
  );
}

module.exports = { users, listings, offers, messages, watchlist, seed };
